/*
  Starter catalogue.
  Only a few fields came from known store examples; verify every specification,
  price and stock status before using it for a sale. The app lets you edit,
  import and export the catalogue directly on the phone.
*/
window.STARTER_PRODUCTS = [
  {
    id: "point-c60-bl",
    name: "POINT C60 BL",
    code: "POINT-C60-BL",
    price: null,
    lumens: 3060,
    watts: null,
    kelvin: "",
    sizeCm: 60,
    category: "ceiling",
    rooms: ["living_room", "bedroom", "hallway"],
    styles: ["modern", "minimal"],
    features: ["main_light", "low_ceiling"],
    ip: "IP20",
    stock: "in_stock",
    location: "Spice Home",
    image: "",
    notes: "Known starter entry: 3060 lm. Verify price, colour temperature and live stock."
  },
  {
    id: "zonda-oto-c60-wh",
    name: "ZONDA OTO C60 WH",
    code: "ZONDA-OTO-C60-WH",
    price: null,
    lumens: null,
    watts: null,
    kelvin: "",
    sizeCm: 60,
    category: "ceiling",
    rooms: ["living_room", "bedroom", "hallway"],
    styles: ["modern", "minimal"],
    features: ["main_light", "low_ceiling"],
    ip: "IP20",
    stock: "display",
    location: "Store display — verify salon",
    image: "",
    notes: "Starter entry based on a previously encountered model. Verify all technical data."
  },
  {
    id: "zonda-demetra-c50-bl",
    name: "ZONDA DĒMETRA C50 BL",
    code: "ZONDA-DEMETRA-C50-BL",
    price: null,
    lumens: null,
    watts: null,
    kelvin: "",
    sizeCm: 50,
    category: "ceiling",
    rooms: ["living_room", "bedroom", "hallway"],
    styles: ["modern", "minimal"],
    features: ["main_light", "low_ceiling"],
    ip: "IP20",
    stock: "display",
    location: "Brīvības iela — verify",
    image: "",
    notes: "Starter entry. Verify all technical data and availability."
  },
  {
    id: "satellite-c60-wh",
    name: "SATELLITE C60 WH",
    code: "SATELLITE-C60-WH",
    price: null,
    lumens: null,
    watts: null,
    kelvin: "",
    sizeCm: 60,
    category: "ceiling",
    rooms: ["living_room", "bedroom"],
    styles: ["modern", "statement"],
    features: ["main_light"],
    ip: "IP20",
    stock: "display",
    location: "Store display — verify salon",
    image: "",
    notes: "Starter entry. Verify all technical data and availability."
  },
  {
    id: "aura-c60-bk",
    name: "AURA C60 BK",
    code: "AURA-C60-BK",
    price: null,
    lumens: null,
    watts: null,
    kelvin: "",
    sizeCm: 60,
    category: "ceiling",
    rooms: ["living_room", "bedroom", "office"],
    styles: ["modern", "minimal"],
    features: ["main_light", "low_ceiling"],
    ip: "IP20",
    stock: "display",
    location: "Store display — verify salon",
    image: "",
    notes: "Starter entry. Verify all technical data and availability."
  },
  {
    id: "wicky-c50-gl",
    name: "WICKY C50 GL",
    code: "WICKY-C50-GL",
    price: null,
    lumens: null,
    watts: null,
    kelvin: "",
    sizeCm: 50,
    category: "ceiling",
    rooms: ["living_room", "bedroom"],
    styles: ["classic", "decorative"],
    features: ["main_light", "statement"],
    ip: "IP20",
    stock: "display",
    location: "Store display — verify salon",
    image: "",
    notes: "Starter entry. Verify all technical data and availability."
  },
  {
    id: "zen-c60-wh",
    name: "ZEN C60 WH",
    code: "ZEN-C60-WH",
    price: null,
    lumens: null,
    watts: null,
    kelvin: "",
    sizeCm: 60,
    category: "ceiling",
    rooms: ["living_room", "bedroom", "office"],
    styles: ["minimal", "modern"],
    features: ["main_light", "low_ceiling"],
    ip: "IP20",
    stock: "display",
    location: "Brīvības iela — verify",
    image: "",
    notes: "Starter entry. Verify all technical data and availability."
  },
  {
    id: "viva-c60-bk",
    name: "VIVA C60 BK",
    code: "VIVA-C60-BK",
    price: null,
    lumens: null,
    watts: null,
    kelvin: "",
    sizeCm: 60,
    category: "ceiling",
    rooms: ["living_room", "bedroom"],
    styles: ["modern", "statement"],
    features: ["main_light"],
    ip: "IP20",
    stock: "in_stock",
    location: "Brīvības iela / warehouse — verify",
    image: "",
    notes: "Starter entry. Verify all technical data and availability."
  },
  {
    id: "cabinet-led-slim-sensor-300",
    name: "CABINET LED SLIM SENSOR 300 mm",
    code: "CABINET-SENSOR-300",
    price: null,
    lumens: null,
    watts: null,
    kelvin: "3000",
    sizeCm: 30,
    category: "cabinet",
    rooms: ["wardrobe", "kitchen", "hallway"],
    styles: ["minimal", "modern"],
    features: ["sensor", "cabinet", "warm", "task_light"],
    ip: "IP20",
    stock: "order",
    location: "Order item",
    image: "",
    notes: "3000 K warm-light sensor strip. Verify current price with logistics."
  },
  {
    id: "cabinet-led-slim-sensor-500",
    name: "CABINET LED SLIM SENSOR 500 mm",
    code: "CABINET-SENSOR-500",
    price: null,
    lumens: null,
    watts: null,
    kelvin: "3000",
    sizeCm: 50,
    category: "cabinet",
    rooms: ["wardrobe", "kitchen", "hallway"],
    styles: ["minimal", "modern"],
    features: ["sensor", "cabinet", "warm", "task_light"],
    ip: "IP20",
    stock: "order",
    location: "Order item",
    image: "",
    notes: "3000 K warm-light sensor strip. Verify current price with logistics."
  },
  {
    id: "milne-led-wall",
    name: "MILNE LED",
    code: "44216/12/30",
    price: null,
    lumens: null,
    watts: null,
    kelvin: "3000",
    sizeCm: null,
    category: "wall",
    rooms: ["bedroom", "hallway", "living_room"],
    styles: ["modern"],
    features: ["accent_light"],
    ip: "IP20",
    stock: "unknown",
    location: "Verify store location",
    image: "",
    notes: "Starter entry from a previously encountered product code. Verify all data."
  },
  {
    id: "orvit-black-wall",
    name: "ORVIT BLACK I KINKIET S",
    code: "7806",
    price: null,
    lumens: null,
    watts: null,
    kelvin: "",
    sizeCm: null,
    category: "wall",
    rooms: ["bedroom", "hallway", "living_room"],
    styles: ["modern", "industrial"],
    features: ["accent_light"],
    ip: "IP20",
    stock: "unknown",
    location: "Verify store location",
    image: "",
    notes: "Starter entry from a previously encountered product code. Verify all data."
  },
  {
    id: "demo-bedroom-ceiling",
    name: "DEMO — Warm bedroom ceiling lamp",
    code: "DEMO-BED-01",
    price: 129,
    lumens: 2800,
    watts: 32,
    kelvin: "3000",
    sizeCm: 48,
    category: "ceiling",
    rooms: ["bedroom"],
    styles: ["modern", "minimal"],
    features: ["main_light", "dimmable", "low_ceiling", "warm"],
    ip: "IP20",
    stock: "in_stock",
    location: "DEMO shelf A1",
    image: "",
    notes: "Demonstration record. Replace with a real product before customer use."
  },
  {
    id: "demo-bathroom-ceiling",
    name: "DEMO — Bathroom ceiling lamp IP44",
    code: "DEMO-BATH-01",
    price: 89,
    lumens: 2200,
    watts: 24,
    kelvin: "4000",
    sizeCm: 35,
    category: "ceiling",
    rooms: ["bathroom"],
    styles: ["modern", "minimal"],
    features: ["main_light", "low_ceiling", "neutral"],
    ip: "IP44",
    stock: "in_stock",
    location: "DEMO shelf B2",
    image: "",
    notes: "Demonstration record. Replace with a real product before customer use."
  },
  {
    id: "demo-reading-wall",
    name: "DEMO — Adjustable bedside reading lamp",
    code: "DEMO-READ-01",
    price: 69,
    lumens: 550,
    watts: 7,
    kelvin: "3000",
    sizeCm: 14,
    category: "wall",
    rooms: ["bedroom", "office"],
    styles: ["modern", "minimal"],
    features: ["reading", "task_light", "adjustable", "warm"],
    ip: "IP20",
    stock: "in_stock",
    location: "DEMO shelf C1",
    image: "",
    notes: "Demonstration record. Replace with a real product before customer use."
  },
  {
    id: "demo-kitchen-pendant",
    name: "DEMO — Three-light kitchen pendant",
    code: "DEMO-KITCH-01",
    price: 175,
    lumens: 2400,
    watts: 30,
    kelvin: "3000",
    sizeCm: 90,
    category: "pendant",
    rooms: ["kitchen", "dining_room"],
    styles: ["modern", "industrial"],
    features: ["task_light", "main_light", "height_adjustable", "warm"],
    ip: "IP20",
    stock: "order",
    location: "DEMO order item",
    image: "",
    notes: "Demonstration record. Replace with a real product before customer use."
  }
];
